MADDR_ROBOT_STATUS_GET = 100
MADDR_ROBOT_STATUS_PUT = 101
MADDR_ROBOT_STATUS_ACT = 102

MADDR_ROBOT_STATUS_GET_COMFIRM = 105
MADDR_ROBOT_STATUS_PUT_COMFIRM = 106
MADDR_ROBOT_STATUS_ACT_COMFIRM = 107

MADDR_BARCODE_SCAN_GET = 110
MADDR_BARCODE_SCAN_REQ = 111

MADDR_BARCODE_SCAN_GET_COMFIRM = 140
MADDR_BARCODE_SCAN_RET = 141

ROBOT_ACTING_WAIT_TIME = 0.5
